{{- $hasInstances := gt (len .Values.instances) 0 }}
{{- $instances := .Values.instances | default (list (dict)) }}
{{- range $idx, $instance := $instances }}
{{- $values := mergeOverwrite (deepCopy $.Values) $instance }}
{{- if and $values.enable $values.enableDeployment }}
{{- $ctx := dict "Values" $values "Release" $.Release "Chart" $.Chart "Capabilities" $.Capabilities "Files" $.Files "Template" $.Template }}
apiVersion: apps/v1
kind: Deployment
{{- $defaultName := $.Release.Name }}
{{- if and $hasInstances (not $values.name) }}
{{- $defaultName = printf "%s-%d" $.Release.Name $idx }}
{{- end }}
{{- $name := $values.name | default $defaultName }}
metadata:
  name: "{{ $name }}"
  labels:
    app.kubernetes.io/name: "{{ $name }}"
    {{- range $key, $value := $values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ $name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ $name }}"
        {{- range $key, $value := $values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: "{{ . }}"
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 1
      {{- if $values.gpu }}
      runtimeClassName: nvidia
      {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $values.dependsOn $values.initContainers }}
      initContainers:
      {{- range $dependency := $values.dependsOn }}
      - name: "{{ include "openadservice.rfc1123CompliantName" (printf "%s-wait-for-%s-%v" $name $dependency.host $dependency.port) }}"
        image: busybox:1.36
        command:
          - sh
          - -ec
          - >
            until nc -z {{ $dependency.host }} {{ $dependency.port }};
            do echo "waiting for '{{ $dependency.host }}:{{ $dependency.port }}'"; sleep 1; done
      {{- end }}
      {{- with $values.initContainers }}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "{{ $name }}"
        image: "{{ $values.image }}"
        imagePullPolicy: "{{ $values.imagePullPolicy }}"
        {{- with $values.command }}
        command:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $values.args }}
        args:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $values.shm }}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        {{- end }}
        env:
        {{- if $values.gpu }}
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        {{- end }}
        {{- if $values.x11Display }}
        - name: DISPLAY
          value: "{{ $values.x11Display }}"
        - name: XAUTHORITY
          value: /.Xauthority
        {{- end }}
        {{- range $key, $value := $values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - name: timezone
          mountPath: /etc/timezone
        - name: localtime
          mountPath: /etc/localtime
        {{- if $values.shm }}
        - name: shared-memory
          mountPath: /dev/shm
        {{- end }}
        {{- if $values.x11XauthorityFile }}
        - name: x11-unix
          mountPath: /tmp/.X11-unix
        - name: xauthority
          mountPath: /.Xauthority
        {{- end }}
        - name: "{{ include "openadservice.rfc1123CompliantName" ("DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5") }}"
          mountPath: /opt/ros/jazzy/share/rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5
          subPath: DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5
        {{- if and $values.rosParamFileMountPath $values.rosParamFileData }}
        - name: "{{ include "openadservice.rfc1123CompliantName" ($values.rosParamFileMountPath | base) }}"
          mountPath: "{{ $values.rosParamFileMountPath }}"
          subPath: "{{ $values.rosParamFileMountPath | base }}"
        {{- end }}
        {{- range $values.volumes }}
        {{- if or (and .data (not (empty (tpl .data $ctx)))) .hostPath .configMapName .image }}
        - name: "{{ include "openadservice.volumeName" .mountPath }}"
          mountPath: "{{ .mountPath }}"
        {{- if or .data .configMapName }}
          subPath: "{{ .configMapKey | default (.mountPath | base) }}"
        {{- else if .image }}
        {{- with .imagePath }}
          subPath: "{{ . }}"
        {{- end }}
          readOnly: true
        {{- end }}
        {{- end }}
      volumes:
      - name: timezone
        hostPath:
          path: /etc/timezone
      - name: localtime
        hostPath:
          path: /etc/localtime
      {{- if $values.shm }}
      - name: shared-memory
        hostPath:
          path: /dev/shm
          type: Directory
      {{- end }}
      {{- if $values.x11XauthorityFile }}
      - name: x11-unix
        hostPath:
          path: /tmp/.X11-unix
      - name: xauthority
        hostPath:
          path: "{{ $values.x11XauthorityFile }}"
      {{- end }}
      - name: "{{ include "openadservice.rfc1123CompliantName" ("DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5") }}"
        configMap:
          name: "{{ include "openadservice.rfc1123CompliantName" (printf "%s-%s" $name ("DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5")) }}"
      {{- if and $values.rosParamFileMountPath $values.rosParamFileData }}
      - name: "{{ include "openadservice.rfc1123CompliantName" ($values.rosParamFileMountPath | base) }}"
        configMap:
          name: "{{ include "openadservice.rfc1123CompliantName" (printf "%s-%s" $name ($values.rosParamFileMountPath | base)) }}"
      {{- end }}
      {{- range $values.volumes }}
      {{- if or (and .data (not (empty (tpl .data $ctx)))) .hostPath .configMapName .image }}
      - name: "{{ include "openadservice.volumeName" .mountPath }}"
      {{- if .data }}
        configMap:
          name: "{{ include "openadservice.inlineConfigMapName" (dict "root" $ctx "mountPath" .mountPath) }}"
      {{- else if .configMapName }}
        configMap:
          name: "{{ tpl .configMapName $ctx }}"
      {{- else if .hostPath }}
        hostPath:
          path: "{{ tpl .hostPath $ctx }}"
      {{- else if .image }}
        image:
          reference: "{{ tpl .image $ctx }}"
          pullPolicy: "{{ $values.imagePullPolicy }}"
      {{- end }}
      {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
