apiVersion: v2
name: zenoh-router
version: 0.2.10
appVersion: 0.2.10
description: Zenoh Router for ROS 2 RMW Zenoh
dependencies:
  - repository: oci://ghcr.io/openads-project/openads-helm
    name: openadservice
    version: 1.0.0
