openadservice:
  image: rwthika/ros2:jazzy-ros-base-alternative-rmw
  args:
  - ros2
  - run
  - rmw_zenoh_cpp
  - rmw_zenohd
  env:
    RMW_IMPLEMENTATION: rmw_zenoh_cpp
    RUST_LOG: zenoh=info,zenoh_transport=debug
    ZENOH_ROUTER_CONFIG_URI: /DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
  volumes:
  - mountPath: /DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
    configMapName: '{{ include "openadservice.rfc1123CompliantName" (printf "%s-%s" (.Values.name | default .Release.Name) "DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5") }}'
  instances:
    node-a:
      nodeSelector:
        kubernetes.io/hostname: worker-a
      zenoh:
        configOverrides:
          listen/endpoints:
          - tcp/[::]:7447
      expose:
      - targetPort: 7447
        port: 7447
    node-b:
      nodeSelector:
        kubernetes.io/hostname: worker-b
      zenoh:
        configOverrides:
          listen/endpoints:
          - tcp/[::]:7448
      expose:
      - targetPort: 7448
        port: 7448

endpoints: []
enableAccessControl: true
allowedRosTopics: []
allowedRosServices: []
allowedRosActions: []
