{{- if .Values.openadservice.enable }}
{{- if .Values.openadservice.enableConfigMap }}
apiVersion: v1
kind: ConfigMap
{{- $name := include "rfc1123CompliantName" (printf "%s-%s" (.Values.openadservice.name | default .Release.Name) ("DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5")) }}
metadata:
  name: "{{ $name }}"
  labels:
    app.kubernetes.io/name: "{{ $name }}"
    {{- range $key, $value := .Values.openadservice.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
{{ tpl ((.Files.Glob "files/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5").AsConfig) $ | indent 2 }}
---
{{- end }}
{{- end }}
