name: helm-push

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

jobs:
  helm-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Push Helm chart
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          chart-folder: openadservice
          force: true
